
--- a/Makefile
+++ b/Makefile
@@ -85,7 +85,7 @@ CPP_Darwin=g++  
 CPP=$(CPP_$(SYSTEM))
 
 #Model specific flags
-MFLAGS_ia64=+DD64
+MFLAGS_ia64=
 MFLAGS_9000/800=+DAportable
 MFLAGS_9000/785=+DAportable
 MFLAGS_i686=
