#!/bin/sh -ex
./Dockerfile.build debian/bullseye  # deb11
./Dockerfile.build debian/buster    # deb10
./Dockerfile.build debian/stretch   # deb9
./Dockerfile.build ubuntu/jammy     # ubu22.04
./Dockerfile.build ubuntu/focal     # ubu20.04
./Dockerfile.build ubuntu/bionic    # ubu18.04
